package com.pr.amaz.model;

public class A {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A.PORT_CODE
     *
     * @mbggenerated
     */
    private String portCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A.PORT_VALUE
     *
     * @mbggenerated
     */
    private String portValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A.PORT_CODE
     *
     * @return the value of A.PORT_CODE
     *
     * @mbggenerated
     */
    public String getPortCode() {
        return portCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A.PORT_CODE
     *
     * @param portCode the value for A.PORT_CODE
     *
     * @mbggenerated
     */
    public void setPortCode(String portCode) {
        this.portCode = portCode == null ? null : portCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A.PORT_VALUE
     *
     * @return the value of A.PORT_VALUE
     *
     * @mbggenerated
     */
    public String getPortValue() {
        return portValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A.PORT_VALUE
     *
     * @param portValue the value for A.PORT_VALUE
     *
     * @mbggenerated
     */
    public void setPortValue(String portValue) {
        this.portValue = portValue == null ? null : portValue.trim();
    }
}