package com.pr.amaz.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.usersex
     *
     * @mbggenerated
     */
    private String usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.reallyname
     *
     * @mbggenerated
     */
    private String reallyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.creattime
     *
     * @mbggenerated
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.powerLevel
     *
     * @mbggenerated
     */
    private String powerlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.rolename
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.attribute1
     *
     * @mbggenerated
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.attribute2
     *
     * @mbggenerated
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.attribnte3
     *
     * @mbggenerated
     */
    private String attribnte3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.userid
     *
     * @return the value of b_user.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.userid
     *
     * @param userid the value for b_user.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.username
     *
     * @return the value of b_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.username
     *
     * @param username the value for b_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.usersex
     *
     * @return the value of b_user.usersex
     *
     * @mbggenerated
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.usersex
     *
     * @param usersex the value for b_user.usersex
     *
     * @mbggenerated
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex == null ? null : usersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.reallyname
     *
     * @return the value of b_user.reallyname
     *
     * @mbggenerated
     */
    public String getReallyname() {
        return reallyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.reallyname
     *
     * @param reallyname the value for b_user.reallyname
     *
     * @mbggenerated
     */
    public void setReallyname(String reallyname) {
        this.reallyname = reallyname == null ? null : reallyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.creattime
     *
     * @return the value of b_user.creattime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.creattime
     *
     * @param creattime the value for b_user.creattime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.powerLevel
     *
     * @return the value of b_user.powerLevel
     *
     * @mbggenerated
     */
    public String getPowerlevel() {
        return powerlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.powerLevel
     *
     * @param powerlevel the value for b_user.powerLevel
     *
     * @mbggenerated
     */
    public void setPowerlevel(String powerlevel) {
        this.powerlevel = powerlevel == null ? null : powerlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.rolename
     *
     * @return the value of b_user.rolename
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.rolename
     *
     * @param rolename the value for b_user.rolename
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.email
     *
     * @return the value of b_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.email
     *
     * @param email the value for b_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.phone
     *
     * @return the value of b_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.phone
     *
     * @param phone the value for b_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.attribute1
     *
     * @return the value of b_user.attribute1
     *
     * @mbggenerated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.attribute1
     *
     * @param attribute1 the value for b_user.attribute1
     *
     * @mbggenerated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.attribute2
     *
     * @return the value of b_user.attribute2
     *
     * @mbggenerated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.attribute2
     *
     * @param attribute2 the value for b_user.attribute2
     *
     * @mbggenerated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.attribnte3
     *
     * @return the value of b_user.attribnte3
     *
     * @mbggenerated
     */
    public String getAttribnte3() {
        return attribnte3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.attribnte3
     *
     * @param attribnte3 the value for b_user.attribnte3
     *
     * @mbggenerated
     */
    public void setAttribnte3(String attribnte3) {
        this.attribnte3 = attribnte3 == null ? null : attribnte3.trim();
    }
}