package com.pr.amaz.mapper;

import com.pr.amaz.model.A;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int insert(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int insertSelective(A record);
}