package com.pr.amaz.mapper;

import com.pr.amaz.model.UserInfo;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);

    /**
     * 根据对象查询用户集合
     * @param userInfo
     * @return
     */
    List<UserInfo> selectUserByPrimaryKey(UserInfo userInfo);
}