server:
  port: 8012
spring:
  mvc:
  #视图配置
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
    #数据源配置
  datasource:
    name: business
    url: jdbc:mysql//193.112.249.196:3306/business
    username: panrui
    password: PanRui1993!
    type: com.alibaba.druid.pool.Driver
    driver-class-name: com.mysql.jdbc.Driver
#mybtis相关配置
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com/pr/amaz/dao
#分页插件的配置
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              